# Generated by Django 3.0.5 on 2020-05-27 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('letter_alternative', models.CharField(max_length=1)),
                ('respuesta', models.CharField(max_length=250)),
                ('estilo', models.IntegerField()),
                ('efectividad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('encabezado', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa_seleccionada',
            fields=[
                ('id_alternativa_seleccionada', models.IntegerField(primary_key=True, serialize=False)),
                ('id_alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Preguntas.Alternativa')),
                ('id_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Feedback.Feedback')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='id_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Preguntas.Pregunta'),
        ),
    ]
