# Generated by Django 3.0.5 on 2020-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0002_auto_20200527_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa_seleccionada',
            name='respuesta_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
