# Generated by Django 3.0.5 on 2020-05-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_efectividad', models.IntegerField()),
                ('total_estilos', models.IntegerField()),
                ('efectividad_del_estilo', models.IntegerField()),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Persona.Persona')),
            ],
        ),
    ]
