# Generated by Django 3.0.5 on 2020-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id_feedback',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
